title: Datenanlyse mit jamovi @ H-BRS
description: Hilfseite für Nutzung von jamovi für typische Datenanalsen im B.Sc.-Studiengang Wirtschaftspsychologie an der H-BRS
theme: just-the-docs

url: https://Malschuetzky.github.io/psy_datenanalyse

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/Malschuetzky/psy_datenanalyse
